# Generated by Django 5.1.7 on 2025-05-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Country',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='users',
            name='Port',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='users',
            name='EmailId',
            field=models.EmailField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='users',
            name='FirstName',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='users',
            name='LastName',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='users',
            name='Password',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='users',
            name='Username',
            field=models.CharField(default='', max_length=40),
        ),
    ]
