# Generated by Django 5.1.7 on 2025-05-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_users_country_users_port_alter_users_emailid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='UserType',
            field=models.CharField(default='', max_length=20),
        ),
    ]
