# Generated by Django 5.1.7 on 2025-05-31 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_lineupform_createdat_lineupform_updatedat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineupform',
            name='CreatedAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lineupform',
            name='UpdatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='saileddata',
            name='CreatedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saileddata',
            name='UpdatedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
