# Generated by Django 5.1.7 on 2025-05-31 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_lineupform_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saileddata',
            name='CreatedAt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='saileddata',
            name='UpdatedAt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
