# Generated by Django 5.1.7 on 2025-05-31 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_saileddata_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saileddata',
            name='CreatedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saileddata',
            name='UpdatedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
